name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Install deps
        run:  |
          python -m pip install '.[tests]'

      - name: Run tests
        run:  |
         python -m pytest .